name: morningstar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cloudinary: ^1.2.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 800

flutter_intl:
  enabled: true
